apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-logistics-api
  namespace: logistics
spec:
  selector:
    matchLabels:
      app: logistics-api
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/tracking/sa/tracking-svc-sa
    to:
    - operation:
        methods: ["GET"]
        paths: ["/v1/routes/*"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-external-to-tracking
  namespace: tracking
spec:
  action: DENY
  rules:
  - from:
    - source:
        notNamespaces: ["logistics", "tracking"]
    to:
    - operation:
        methods: ["POST"]
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: tracking-strict
  namespace: tracking
spec:
  mtls:
    mode: STRICT
